blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/Enreign/athena/blob/main/CONTRIBUTING.md
    about: For usage questions, please read CONTRIBUTING.md before opening an issue.
